spring:
  application:
    name: seat-reservation
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/seats
    username: seats
    password: seats-dev
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          batch_size: 50
        order_inserts: true
  jackson:
    property-naming-strategy: SNAKE_CASE

server:
  port: 8080
